<a href="https://colab.research.google.com/github/ozair247/flyrank-ml-internship/blob/main/work/notebooks/w01_research_question.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import pandas as pd
import os

# Targeting the specifically uploaded filename
filename = 'content_refresh_anonymized (1).csv'

try:
    if os.path.exists(filename):
        df = pd.read_csv(filename)
        print(f"Successfully loaded: {filename}")
        print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")
        display(df.head())
    else:
        print(f"Could not find {filename}. Please check the file browser on the left.")
except Exception as e:
    print(f"Error loading data: {e}")

Successfully loaded: content_refresh_anonymized (1).csv
Rows: 30000, Columns: 44


,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7


# ML-02 — Research Question and Provisional Lane

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ozair247/flyrank-ml-internship/blob/main/work/notebooks/w01_research_question.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My Lane and Why

I have chosen **Lane 2: Refresh / Content Opportunity Scoring**.

I selected this lane because the data shows a clear need for prioritization. With **30,000 content units** in the dataset, a human team cannot manually review every page. The average content age is over **8 months (~256 days)**, which suggests significant content decay risk. Since the median page still receives **~731 impressions** over 90 days, there is substantial existing traffic at risk of being lost. A machine learning approach in this lane can combine signals like engagement rate, CTR, and age to rank exactly which of these 30,000 pages an editor should fix first, saving time and recovering traffic.

In [ ]:
# no code required.

## 2. The Question: Decision, Action, and Cost of a Wrong Call

**The Decision:**  
Which specific pages should be prioritized for a content refresh to prevent traffic decline?

**The Action:**  
An SEO content specialist will take the top 50 ranked pages from the model's output and rewrite the headlines, update outdated statistics, and improve internal linking before moving to lower-ranked pages.

**The Cost of a Wrong Recommendation:**  
- **False Positive (Wasting time):** If the model recommends a page that is actually healthy, the team wastes ~2 hours editing content that didn't need it.  
- **False Negative (Missing a decline):** If the model misses a page that is about to crash, the client loses the ~731 median impressions (and potential clicks) that page was generating, leading to a direct loss in organic visibility and revenue.

**Why this isn't just "train a model":**  
This is a decision-support system, not a black-box prediction. The goal is to understand *why* a page is declining (low CTR, stale age, weak engagement) and provide a transparent, ranked list so a human makes the final call. The model serves the editor, it does not replace them.

In [ ]:
# no code required.

## 3. Quick Look at the Data (2-3 Real Numbers)

The dataset contains exactly **30,000** rows of anonymized search performance data.

The key numbers supporting my lane choice are:

- **Scale of the problem:** With 30,000 units, manual review is impossible—prioritization is mandatory.
- **Audience exposure:** The median page receives **731 impressions** over 90 days. This means even "average" pages have a real audience, so fixing them matters.
- **Decay signal:** The average content age is **256 days** (~8 months). Stale content is abundant, and updating it could recapture the impressions currently being lost to newer competitors.
- **Engagement gap:** The average page only gets **~16 clicks** in 90 days. This indicates a massive opportunity to improve metadata and CTR.

These numbers prove that this lane is worth 7 weeks: we have a large inventory, active traffic on the line, and clear signs of aging and underperformance that a smart ranking can fix.

In [39]:
# 3. Quick look at the data (Supporting numbers)
# Using the identified column names to generate supporting statistics.

if 'df' in locals():
    # 1. Unique content units
    unique_pages = df['content_id'].nunique()

    # 2. Average clicks in the last 90 days
    avg_clicks_90d = df['clicks_90d'].mean()

    # 3. Median impressions in the last 90 days
    med_impressions_90d = df['impressions_90d'].median()

    print(f"--- Supporting Numbers for Research Question ---")
    print(f"1. Total Unique Content Units: {unique_pages}")
    print(f"2. Average Clicks (90d): {avg_clicks_90d:.2f}")
    print(f"3. Median Impressions (90d): {med_impressions_90d:.2f}")

    # Optional: Look at content age distribution to see if 'decay' is a viable lane
    if 'content_age_days' in df.columns:
        print(f"4. Average Content Age (days): {df['content_age_days'].mean():.1f}")

    display(df[['clicks_90d', 'impressions_90d', 'search_volume']].describe())
else:
    print("Error: 'df' not found. Please run the data loading cell first.")

--- Supporting Numbers for Research Question ---
1. Total Unique Content Units: 30000
2. Average Clicks (90d): 16.10
3. Median Impressions (90d): 731.00
4. Average Content Age (days): 256.2


,clicks_90d,impressions_90d,search_volume
count,30000.000000,30000.000000,27532.000000
mean,16.097333,5200.366300,158.882391
std,75.076958,16838.019547,1518.270825
min,0.000000,1.000000,0.000000
25%,0.000000,81.000000,0.000000
50%,1.000000,731.000000,10.000000
75%,7.000000,3615.250000,20.000000
max,4178.000000,517715.000000,74000.000000


## 4. Careful Words: What I Can and Can't Claim

**What I CAN claim (Directional / Observed):**  
- "In this dataset, pages with lower CTR and higher age show a stronger association with traffic decline."  
- "The model provides a ranked queue that helps editors focus on pages with the highest observed risk."  
- "These rankings are decision-support, based on historical patterns in this specific snapshot."

**What I CANNOT claim (Causal / Absolute):**  
- "I have proven why Google ranks pages this way."  
- "Refreshing these pages guarantees a recovery."  
- "This model works for every website, industry, or time period."  

**Honest Limitation:**  
This project is purely observational. A page might decline due to seasonality, a Google update, or competitor activity—factors not captured in this data. I am building a prioritization tool, not a crystal ball.

In [ ]:
# no code required.


## 5. Self-Check

Before submitting, I confirmed:

- [x] Picked a specific lane (Lane 2: Refresh / Content Opportunity Scoring).
- [x] Named the decision (which pages to review first).
- [x] Named the action (editor rewrites the top 50 pages).
- [x] Explained the cost of being wrong (wasted time vs. lost revenue/traffic).
- [x] Backed my choice with 3 real numbers from the starter dataset (30k rows, 731 median impressions, 256 avg age).
- [x] Explained why ML helps (combines weak signals to rank 30k pages transparently).
- [x] Used careful, honest language (observed/directional, not causal).
- [x] No client names, URLs, or private queries appear in this notebook.